name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.0
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  google_sign_in: ^7.2.0
  meta: ^1.8.0

dev_dependencies:
  firebase_auth_platform_interface: ^8.1.3
  firebase_core_platform_interface: ^6.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.7
  very_good_analysis: ^10.0.0
