// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIQeU9ArlE3RYBcLiNJLreND_CjA99RCg',
    appId: '1:337905744833:android:5c2e112156a898c0874d40',
    messagingSenderId: '337905744833',
    projectId: 'bunchup-2025',
    databaseURL: 'https://bunchup-2025-default-rtdb.europe-west1.firebasedatabase.app',
    androidClientId: '337905744833-tq7jiiq2mu5t0olrmhejrrjafb996taj.apps.googleusercontent.com',
    iosClientId: '337905744833-f9pummagsm23isrejo42kr884va8q8o1.apps.googleusercontent.com',
    storageBucket: 'bunchup-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgySBJd_dN0xlZw1Gsu4h89qNRlA85PKQ',
    appId: '1:337905744833:ios:575661627d8da55f874d40',
    messagingSenderId: '337905744833',
    projectId: 'bunchup-2025',
    databaseURL: 'https://bunchup-2025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bunchup-2025.firebasestorage.app',
    androidClientId: '337905744833-tq7jiiq2mu5t0olrmhejrrjafb996taj.apps.googleusercontent.com',
    iosClientId: '337905744833-f9pummagsm23isrejo42kr884va8q8o1.apps.googleusercontent.com',
    iosBundleId: 'com.github.bunchup.bunchup',
  );

}